//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 08:22:14 AM EET 
//


package ua.nure.order.entity.meal;

import ua.nure.order.entity.Product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Meal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Meal">
 *   &lt;complexContent>
 *     &lt;extension base="{http://order.nure.ua/entity/}Entity">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ingredient" type="{http://order.nure.ua/entity/book/}Ingredient" maxOccurs="unbounded"/>
 *         &lt;element name="calory" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="ISBN-[0-9]{5,5}-[0-9]{4,4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="price" type="{http://order.nure.ua/entity/book/}Price"/>
 *         &lt;element name="category" type="{http://order.nure.ua/entity/book/}Category"/>
 *         &lt;element name="count">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Meal", propOrder = {
    "title",
		"ingredient",
		"calory",
"price",
    "category",
    "count",
    "description",

})
public class Meal extends Product {

	@XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected List<Ingredient> ingredient;
    protected String calory;
    @XmlElement(required = true, defaultValue = "none")
    protected Category category;
    @XmlElement(defaultValue = "0")
    protected int count;
    protected double price;
    protected String description;

    public Meal() {
		super();
	}

	public Meal(String title, List<Ingredient> ingredient, String calory, double price,  Category category, int count) {
		super();
		this.title = title;
		this.ingredient = ingredient;
		this.calory = calory;
this.price = price;
		this.category = category;
		this.count = count;
	}

	public Meal(Integer id, String title, List<Ingredient> ingredient,  String calory, double price,Category category,
				int count) {
		super(id);
		this.title = title;
		this.ingredient = ingredient;
		this.calory = calory;
		this.price = price;
		this.category = category;
		this.count = count;
	}

	/**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the ingredient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ingredient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIngredient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ingredient }
     * 
     * 
     */
    public List<Ingredient> getIngredient() {
        if (ingredient == null) {
            ingredient = new ArrayList<Ingredient>();
        }
        return this.ingredient;
    }

    public String ingredients() {
    	if (ingredient == null) {
    		ingredient = new ArrayList<Ingredient>();
    		return "";
    	}
    	StringBuilder res = new StringBuilder();
    	for (Ingredient a : ingredient) {
			res.append(a.getTitle());
			res.append(",");
		}
    	res.setLength(res.length() - 1);
    	return res.toString();
    }
    
    public void setIngredient(String ingredient) {
		String[] ingredients = ingredient.split("\\s*,\\s*");
		ArrayList<Ingredient> items = new ArrayList<>();
		for (String a : ingredients) {
			items.add(new Ingredient(a));
		}
		this.ingredient = items;
	}

	/**
     * Gets the value of the calory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalory() {
        return calory;
    }

    /**
     * Sets the value of the calory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalory(String value) {
        this.calory = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(double value) {
        this.price = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}





	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Meal [id=");
		builder.append(id);
		builder.append(", price=");
		builder.append(price);
		builder.append(", title=");
		builder.append(title);

		builder.append(", ingredient=");
		builder.append(ingredient);
		builder.append(", calory=");
		builder.append(calory);
		builder.append(", category=");
		builder.append(category);
		builder.append(", count=");
		builder.append(count);
		builder.append("]\n");
		return builder.toString();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (!(obj instanceof Meal))
			return false;
		Meal other = (Meal) obj;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		return true;
	}

}
